import type { AssessmentPayload, AssessmentResponse, CancerAssessment } from "@/lib/assessment-types"
import { CANCER_TYPE_LABELS, comparePriorityDescending, getPriorityConfig } from "@/lib/priority-config"

function screeningHistory(input: AssessmentPayload, cancerType: CancerAssessment["cancer_type"]) {
  if (cancerType === "breast") {
    if (!input.breast.screened_before) return "No previous screening recorded"
    const years = input.breast.years_since_cbe
    return years === null ? "Previous screening recorded; interval not supplied" : `Previous screening recorded approximately ${years} year${years === 1 ? "" : "s"} ago`
  }

  const record = cancerType === "oral" ? input.oral : input.cervical
  if (!record.screened_before) return "No previous screening recorded"
  const years = record.years_since_screening
  return years === null ? "Previous screening recorded; interval not supplied" : `Previous screening recorded approximately ${years} year${years === 1 ? "" : "s"} ago`
}

export function ReferralSummary({
  result,
  input,
  completedAt,
}: {
  result: AssessmentResponse
  input: AssessmentPayload
  completedAt?: string | null
}) {
  const pathways: CancerAssessment[] = [
    result.results.oral,
    result.results.breast,
    result.results.cervical,
  ].sort((a, b) => comparePriorityDescending(a.priority, b.priority))
  const completedDate = completedAt ? new Date(completedAt) : null

  return (
    <section id="referral-summary" className="referral-summary hidden bg-surface text-foreground print:block" aria-label="Printable referral summary">
      <header className="referral-print-header flex items-start justify-between gap-6 border-b-2 border-foreground pb-4">
        <div>
          <p className="text-xs font-semibold uppercase tracking-widest">Oncology Assessment &amp; Screening Information System</p>
          <h1 className="mt-1 text-2xl font-semibold">O.A.S.I.S. Referral Summary</h1>
        </div>
        <div className="text-right text-xs leading-relaxed">
          <p><strong>Assessment ID:</strong> {result.assessment_id}</p>
          <p><strong>Date:</strong> {completedDate ? completedDate.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "Not recorded"}</p>
        </div>
      </header>

      <section className="grid grid-cols-2 gap-x-8 gap-y-2 border-b border-border py-4 text-sm">
        <p><strong>Patient code:</strong> {result.patient_code}</p>
        <p><strong>Age:</strong> {input.patient.age}</p>
        <p><strong>Sex at birth:</strong> {input.patient.sex_at_birth === "unknown" ? "Unknown / not recorded" : input.patient.sex_at_birth.charAt(0).toUpperCase() + input.patient.sex_at_birth.slice(1)}</p>
        <p><strong>Overall priority:</strong> {getPriorityConfig(result.overall_priority).label}</p>
      </section>

      <div className="flex flex-col gap-5 py-5">
        {pathways.map((pathway) => (
          <section key={pathway.cancer_type} className="referral-pathway border border-border p-4">
            <div className="flex items-center justify-between gap-4 border-b border-border pb-2">
              <h2 className="text-base font-semibold">{CANCER_TYPE_LABELS[pathway.cancer_type]} cancer pathway</h2>
              <p className="text-sm font-semibold">{getPriorityConfig(pathway.priority).label} · Index {pathway.priority_score}/100</p>
            </div>
            <div className="mt-3 grid grid-cols-2 gap-5 text-xs leading-relaxed">
              <div className="flex flex-col gap-3">
                <div><h3 className="font-semibold">Red flags</h3><p>{pathway.red_flags.length ? pathway.red_flags.join("; ") : "None recorded"}</p></div>
                <div><h3 className="font-semibold">Key reasons</h3><ul className="pl-4">{pathway.reasons.length ? pathway.reasons.map((reason) => <li className="list-disc" key={reason.factor}>{reason.factor}: {reason.effect}</li>) : <li>None recorded</li>}</ul></div>
              </div>
              <div className="flex flex-col gap-3">
                <div><h3 className="font-semibold">Recommended next action</h3><p>{pathway.recommended_action}</p></div>
                <div><h3 className="font-semibold">Screening history</h3><p>{screeningHistory(input, pathway.cancer_type)}</p></div>
              </div>
            </div>
          </section>
        ))}
      </div>

      <p className="border-y border-border py-3 text-xs font-medium leading-relaxed">This referral summary is generated by a clinical decision-support prototype and must be reviewed by a qualified healthcare professional.</p>
      <p className="mt-3 text-xs leading-relaxed">{result.disclaimer} A low Screening Priority Index does not rule cancer out.</p>

      <section className="mt-8 grid grid-cols-2 gap-x-10 gap-y-8 text-xs">
        <p className="border-b border-foreground pb-2">Clinician name / signature</p>
        <p className="border-b border-foreground pb-2">Facility</p>
        <p className="border-b border-foreground pb-2">Follow-up date</p>
        <p className="border-b border-foreground pb-2">Referral status</p>
      </section>
    </section>
  )
}
